<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Categories extends Admin_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categories_model');
    }

    /*
     * Listing of categories
     */
    function index()
    {

        $this->load->library('form_validation');

        $this->form_validation->set_rules('name', 'Name', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'status' => ACTIVE,
                'parent_id' => $this->input->post('parent_cat_id'),
                'name' => $this->input->post('name'),
                'created_by' => $this->session->userdata('id')
            );

            $this->db->insert('categories', $params);
            redirect('categories');
        } else {
            $this->db->select('*');
            $this->db->where('parent_id=','');
            $this->db->where('parent_id=',0);
            $data['categories'] = $this->db->get('categories')->result_array();
            //print_r($this->db->last_query()); exit;
            $data['_view'] = 'categories/index';
            $this->load->view('layouts/main', $data);
        }
    }

    function get_list()
    {
        $columns = array(
            0 => 'id',
            1 => 'cat_name',
            2 => 'parent_cat_name',
            3 => 'date_created',
            4 => 'status',
            5 => 'actions',
        );

        $limit = $this->input->post('length');
        $start = $this->input->post('start');
        $order = $columns[$this->input->post('order')[0]['column']];
        $dir = $this->input->post('order')[0]['dir'];

        $totalData = $this->Categories_model->get_all_Categories_count();

        $totalFiltered = $totalData;

        if (empty($this->input->post('search')['value'])) {
            $posts = $this->Categories_model->get_all_Categories($limit, $start, $order, $dir);
        } else {
            $search = $this->input->post('search')['value'];

            $posts =  $this->Categories_model->categories_search($limit, $start, $search, $order, $dir);

            $totalFiltered = $this->Categories_model->categories_search_count($search);
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                $parentCatName = $this->Categories_model->get_parent_cat_name($post->parent_id);
                if(empty($parentCatName)){
                    $catName = "<b>Parent Category</b>";
                } else {
                    $catName = $parentCatName['name'];
                }
                $nestedData['id'] = $post->id;
                $nestedData['cat_name'] =$post->name;
                $nestedData['parent_cat_name'] = $catName;
                $nestedData['date_created'] = date('j M Y', strtotime($post->created_date));
                $nestedData['status'] = ($post->status == 1) ? "<button class='btn btn-success btn-xs btn-status' name='status-active'  code='".$post->id."'>Active</button>" : "<button class='btn btn-danger btn-xs btn-status' name='status-suspend' code='".$post->id."'>Suspened</button>";
                $nestedData['actions'] = "<button class='btn btn-warning btn-xs btn-edit' parentCatId='".$post->parent_id."' code='".$post->id."'>Edit</button>&nbsp;<button class='btn btn-danger btn-xs btn-delete' name='delete' code='".$post->id."'>Delete</button>";

                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw"            => intval($this->input->post('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );

        echo json_encode($json_data);
    }
    
    public function update_categories($id)
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('name', 'Category Name', 'required');
        
        if ($this->form_validation->run()) {
            $this->Categories_model->update_category($id,[
                'parent_id' => $this->input->post('parent_id'),
                'name' => $this->input->post('name'),
                'created_by' => $this->session->userdata('id')
            ]);
        } else {
            http_response_code(400);
            echo json_encode($this->form_validation->error_string(" "," "));
        }
        
        
    }

       

 /*
     * Update Status category
     */
      function updateStatus($id)
    {
      $status=$this->input->post('status');
      // ($status==1) ? 'ACTIVE':
       $this->Categories_model->update_category($id,[
                'status' => $status
            ]);
      // echo $status;exit;  
    }   
    /*
     * Deleting category
     */
    function remove($id)
    {
        $category = $this->Categories_model->get_parent_cat_name($id);

        // check if the category exists before trying to delete it
        if (isset($category['id'])) {
            $this->Categories_model->delete_category($id);
            redirect('category/index');
        } else
            show_error('The category you are trying to delete does not exist.');
    }
}
