<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home_770x320 extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Home_770x320_model');
    } 

    /*
     * Listing of home_770x320
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('home_770x320/index?');
        $config['total_rows'] = $this->Home_770x320_model->get_all_home_770x320_count();
        $this->pagination->initialize($config);

        $data['home_770x320'] = $this->Home_770x320_model->get_all_home_770x320($params);
        
        $data['_view'] = 'home_770x320/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new home_770x320
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'created_by' => $this->input->post('created_by'),
				'date_created' => $this->input->post('date_created'),
				'image_name' => $this->input->post('image_name'),
            );
            
            $home_770x320_id = $this->Home_770x320_model->add_home_770x320($params);
            redirect('home_770x320/index');
        }
        else
        {            
            $data['_view'] = 'home_770x320/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a home_770x320
     */
    function edit($id)
    {   
        // check if the home_770x320 exists before trying to edit it
        $data['home_770x320'] = $this->Home_770x320_model->get_home_770x320($id);
        
        if(isset($data['home_770x320']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'created_by' => $this->input->post('created_by'),
					'date_created' => $this->input->post('date_created'),
					'image_name' => $this->input->post('image_name'),
                );

                $this->Home_770x320_model->update_home_770x320($id,$params);            
                redirect('home_770x320/index');
            }
            else
            {
                $data['_view'] = 'home_770x320/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The home_770x320 you are trying to edit does not exist.');
    } 

    /*
     * Deleting home_770x320
     */
    function remove($id)
    {
        $home_770x320 = $this->Home_770x320_model->get_home_770x320($id);

        // check if the home_770x320 exists before trying to delete it
        if(isset($home_770x320['id']))
        {
            $this->Home_770x320_model->delete_home_770x320($id);
            redirect('home_770x320/index');
        }
        else
            show_error('The home_770x320 you are trying to delete does not exist.');
    }
    
}
