<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Home extends Admin_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    function index()
    {
        $data['home'] = $this->db->get_where('home', array('id'=>1))->row_array();
        $data['_view'] = 'home';
        $this->load->view('layouts/main', $data);
    }

  
    function update_770320()
    {
        if ($_FILES['770320']['name'] != '') {
            $config['upload_path'] = $_SERVER['DOCUMENT_ROOT'] . '/laptop_parts/images/home/';
            $config['allowed_types'] = 'gif|jpg|png|jepg|JPG|PNG|JPEG';
            $config['max_size'] = 2000;
            $config['max_width'] = 1280;
            $config['max_height'] = 1280;

            $this->load->library('upload', $config);

            if ($this->upload->do_upload('770320')) {
                $img_data = $this->upload->data();
                $params['770x320'] = $img_data['file_name'];
                $this->db->where('id',1);
                $this->db->update('home',$params);
                redirect('home');
            } else {
                print_r($this->upload->display_errors());
            }
        }
    }
    function update_380320()
    {
        if ($_FILES['380320']['name'] != '') {
            $config['upload_path'] = $_SERVER['DOCUMENT_ROOT'] . '/laptop_parts/images/home/';
            $config['allowed_types'] = 'gif|jpg|png|jepg|JPG|PNG|JPEG';
            $config['max_size'] = 2000;
            $config['max_width'] = 1280;
            $config['max_height'] = 1280;

            $this->load->library('upload', $config);

            if ($this->upload->do_upload('380320')) {
                $img_data = $this->upload->data();
                $params['380x320'] = $img_data['file_name'];
                $this->db->where('id',1);
                $this->db->update('home',$params);
                redirect('home');
            } else {
                print_r($this->upload->display_errors());
            }
        }
    }
}
