<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Part extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
    }

    function search_part()
    { 
        $data['brands'] = $this->db->get('brand')->result_array();
        $data['_view'] = 'parts/search_part';
        $this->load->view('layouts/main',$data);
    }

    function ajax_get_series($brand_id){
        $series = $this->db->get_where('series', array('brand_id' => $brand_id))->result_array();
        foreach ($series as $key => $value) {
            echo '<a href="javascript:void(0)" onclick="get_models('.$value["id"].')" class="list-group-item list-group-item-action hvr-shadow-radial animate__animated animate__fadeInUp _'.($key+1).'">'.$value['name'].'</a>';
        }
    }

    function get_models($series_id){
        $models = $this->db->get_where('model', array('series_id' => $series_id))->result_array();
        foreach ($models as $key => $value) {
            echo '<a href="javascript:void(0)" onclick="search_parts('.$value["id"].')" class="list-group-item list-group-item-action hvr-shadow-radial animate__animated animate__fadeInUp _'.($key+1).'">'.$value['name'].'</a>';
        }
    }
}
