<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Brand_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    function get_all_brand_count()
    {
        $query = $this
            ->db
            ->get('brand');

        return $query->num_rows();
    }

 function getBrand()
    {
        $query = $this
            ->db
            ->get('brand');
            $output='';
        if ($query->num_rows() > 0) {
            foreach($query->result() as $row)
            {
                $output.='<option>'.$row->name.'</option>';
                                // echo ;
            } 
        } else {
            return null;
        }
    }

    /*
     * Get all brand
     */
    function get_all_brand($limit, $start, $col, $dir)
    {
           $this->db->select('brand.*,category.name AS categoryName, category.id as categoryID,sub_category.name as subCatName, sub_category.id as subCatID');
        $this->db->join('categories as category', 'category.id = brand.category_id', 'inner join');
        $this->db->join('categories as sub_category', 'sub_category.id = brand.sub_category_id', 'inner join');
         // return $query->row_array();
        $query = $this
            ->db
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('brand');

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function brand_search($limit,$start,$search,$col,$dir)
    {
        $query = $this
                ->db
                ->like('id',$search)
                ->or_like('name',$search)
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('brand');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function brand_search_count($search)
    {
        $query = $this
                ->db
                ->like('id',$search)
                ->or_like('name',$search)
                ->get('brand');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_brand($params)
    {
        $this->db->insert('brand', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }
}
