<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Categories_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    
    function get_all_Categories_count()
    {
        $query = $this
            ->db
            ->get('categories');

        return $query->num_rows();
    }
    

    function get_all_Categories($limit, $start, $col, $dir)
    {
        $this->db->select('*');
        $query = $this
            ->db
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('categories');

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }
    function categories_search($limit, $start, $search, $col, $dir)
    {
        $this->db->select('*');
        $query = $this
            ->db
            ->like('name', $search)
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('categories');


        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function categories_search_count($search)
    {
        $this->db->select('*');
        $query = $this
            ->db
            ->like('name', $search)
            ->get('categories');

        return $query->num_rows();
    }
    

    /*
     * function to update categories
     */
    function update_categories($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('categories', $params);
    }

    /*
     * function to delete categories
     */
    function delete_categories($id)
    {
        return $this->db->delete('categories', array('id' => $id));
    }

    function get_parent_cat_name($id)
    {
        return $this->db->get_where('categories', array('id' => $id))->row_array();
    }
}
