<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home_380x320_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get home_380x320 by id
     */
    function get_home_380x320($id)
    {
        return $this->db->get_where('home_380x320',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all home_380x320 count
     */
    function get_all_home_380x320_count()
    {
        $this->db->from('home_380x320');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all home_380x320
     */
    function get_all_home_380x320($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('home_380x320')->result_array();
    }
        
    /*
     * function to add new home_380x320
     */
    function add_home_380x320($params)
    {
        $this->db->insert('home_380x320',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update home_380x320
     */
    function update_home_380x320($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('home_380x320',$params);
    }
    
    /*
     * function to delete home_380x320
     */
    function delete_home_380x320($id)
    {
        return $this->db->delete('home_380x320',array('id'=>$id));
    }
}
