<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Model_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get model by id
     */
    function get_model($id)
    {
        return $this->db->get_where('model', array('id' => $id))->row_array();
    }

    /*
     * Get all model count
     */
    function get_all_model_count()
    {
        $query = $this
            ->db
            ->get('model');

        return $query->num_rows(); 
    }

    /*
     * Get all model
     */
    function get_all_model($limit, $start, $col, $dir)
    {
        $this->db->select('model.*, series.name as series_name, brand.name as brand_name');
        $this->db->join('series', 'series.id = model.series_id', 'left outer');
        $this->db->join('brand', 'brand.id = series.brand_id', 'left outer');
        $query = $this
            ->db
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('model');

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }
    function model_search($limit, $start, $search, $col, $dir)
    {
        $this->db->select('model.*, series.name as series_name, brand.name as brand_name');
        $this->db->join('series', 'series.id = model.series_id', 'left outer');
        $this->db->join('brand', 'brand.id = series.brand_id', 'left outer');
        $query = $this
            ->db
            ->like('model.id', $search)
            ->or_like('series.name', $search)
            ->or_like('brand.name', $search)
            ->or_like('model.name', $search)
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('model');


        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function model_search_count($search)
    {
        $this->db->select('model.*, series.name as series_name, brand.name as brand_name');
        $this->db->join('series', 'series.id = model.series_id', 'left outer');
        $this->db->join('brand', 'brand.id = series.brand_id', 'left outer');
        $query = $this
            ->db
            ->like('model.id', $search)
            ->or_like('series.name', $search)
            ->or_like('brand.name', $search)
            ->or_like('model.name', $search)
            ->get('model');

        return $query->num_rows();
    }
    /*
     * function to add new model
     */
    function add_model($params)
    {
        $this->db->insert('model', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update model
     */
    function update_model($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('model', $params);
    }

    /*
     * function to delete model
     */
    function delete_model($id)
    {
        return $this->db->delete('model', array('id' => $id));
    }
}
