<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_Controller extends CI_Controller {

    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('id')){
            redirect('login');
        }
    }

}
